require("lze").load({
  { import = "plugins.tokyonight" },
  { import = "plugins.lualine" },
  { import = "plugins.blink-cmp" },
  { import = "plugins.lsp" },
  { import = "plugins.plenary" },
  { import = "plugins.treesitter" },
  { import = "plugins.nonels" },
  { import = "plugins.telescope" },
  { import = "plugins.snacks" },
  { import = "plugins.notify" },
  { import = "plugins.nvim-autopairs" },
  { import = "plugins.oil" },
  { import = "plugins.yazi" },
  { import = "plugins.trouble" },
  { import = "plugins.otter" },
  { import = "plugins.obsidian" },
})
